wxapkg_ROOT = ""
mac_unpacked_wxapkg_ROOT = "/Users/jianjia/Documents/projects/mini-app/WeMinT_dataset/groundtruth/miniprograms"
mac_org_groundtruth_ROOT = "/Users/jianjia/Documents/projects/mini-app/WeMinT_dataset/groundtruth_org/groundtruth/miniprograms"
unpacked_wxapkg_ROOT = "/media/data4/jianjia_data4/miniapp_data/WeMinT_dataset/groundtruth/miniprograms"
org_groundtruth_ROOT = "/media/data4/jianjia_data4/miniapp_data/WeMinT_dataset/groundtruth_org/groundtruth/miniprograms"
wxapkg_ROOT = "/media/data4/jianjia_data4/miniapp_data/wxapkgs-42w"
wxapkg_unpacked_ROOT = "/media/data4/jianjia_data4/miniapp_data/wxapkgs-42w-unpacked"
WORKING_APPIDS = ["wx4e1b2aca85a4de6d", "wx4ce9c3cff6c3c610", "wx0bc8123197e70985", "wx4b1dfa2b8f503e6f", "wxf6539b695e8334a1", "wxd92217a38ebcdf68"]
TIMEOUT_APPIDS = []