# all components cited from source:
# https://developers.weixin.qq.com/miniprogram/dev/component/cover-image.html
ALL_API_DEFINED_COMPONENTS = {
    "视图容器": [
        "cover-image",
        "cover-view",
        "match-media",
        "movable-area",
        "movable-view",
        "page-container",
        "root-portal",
        "scroll-view",
        "swiper",
        "swiper-item",
        "view",
    ],
    "基础内容": ["icon", "progress", "rich-text", "text"],
    "表单组件": [
        "button",
        "checkbox",
        "checkbox-group",
        "editor",
        "form",
        "input",
        "keyboard-accessory",
        "label",
        "picker",
        "picker-view",
        "picker-view-column",
        "radio",
        "radio-group",
        "slider",
        "switch",
        "textarea",
    ],
    "Skyline-手势系统": [
        "double-tap-gesture-handler",
        "force-press-gesture-handler",
        "horizontal-drag-gesture-handler",
        "long-press-gesture-handler",
        "pan-gesture-handler"
        "scale-gesture-handler"
        "tap-gesture-handler"
        "vertical-drag-gesture-handler",
    ],
    "Skyline-Other": [
        "draggable-sheet",
        "grid-builder",
        "grid-view",
        "list-builder",
        "list-view",
        "nested-scroll-body",
        "nested-scroll-header",
        "open-container",
        "share-element",
        "snapshot",
        "span",
        "sticky-header",
        "sticky-section",
    ],
    "导航": ["functional-page-navigator", "navigator"],
    "媒体组件": [
        "audio",
        "camera",
        "channel-live",
        "channel-video",
        "image",
        "live-player",
        "live-pusher",
        "video",
        "voip-room",
    ],
    "地图": ["map"],
    "画布": ["canvas"],
    "开放能力": [
        "ad",
        "ad-custom",
        "official-account",
        "open-data",
        "store-home",
        "store-product",
        "web-view",
    ],
    "原生组件说明": ["native-component"],
    "无障碍访问": ["aria-component"],
    "导航栏": ["navigation-bar"],
    "页面属性配置节点": ["page-meta"],
    "不太懂但好像算assume的component": ["slot", "block", "div"],
}
